-- Generated by Oracle SQL Developer Data Modeler 4.1.1.888
--   at:        2024-10-06 16:00:11 PKT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g




CREATE TABLE courses
  (
    course_id                 NUMBER NOT NULL ,
    course_name               VARCHAR2 (50) NOT NULL ,
    department                VARCHAR2 (50) NOT NULL ,
    instructor_id             NUMBER NOT NULL ,
    instructors_instructor_id NUMBER NOT NULL
  ) ;
ALTER TABLE courses ADD CONSTRAINT courses_PK PRIMARY KEY ( course_id ) ;


CREATE TABLE exam_enrollments
  (
    enrollment_id       NUMBER NOT NULL ,
    student_id          NUMBER NOT NULL ,
    exam_id             NUMBER NOT NULL ,
    attendance          CHAR (1) NOT NULL ,
    exams_exam_id       NUMBER NOT NULL ,
    students_student_id NUMBER NOT NULL
  ) ;
ALTER TABLE exam_enrollments ADD CONSTRAINT exam_enrollments_PK PRIMARY KEY ( enrollment_id ) ;


CREATE TABLE exams
  (
    exam_id           NUMBER NOT NULL ,
    course_id         NUMBER NOT NULL ,
    exam_type         VARCHAR2 (50) NOT NULL ,
    exam_date         DATE NOT NULL ,
    start_time        DATE NOT NULL ,
    end_time          DATE NOT NULL ,
    location          VARCHAR2 (50) NOT NULL ,
    courses_course_id NUMBER NOT NULL
  ) ;
ALTER TABLE exams ADD CONSTRAINT exams_PK PRIMARY KEY ( exam_id ) ;


CREATE TABLE instructors
  (
    instructor_id   NUMBER NOT NULL ,
    instructor_name VARCHAR2 (50) NOT NULL
  ) ;
ALTER TABLE instructors ADD CONSTRAINT instructors_PK PRIMARY KEY ( instructor_id ) ;


CREATE TABLE make_up_exams
  (
    make_up_id          NUMBER NOT NULL ,
    student_id          NUMBER NOT NULL ,
    exam_id             NUMBER NOT NULL ,
    make_up_date        DATE NOT NULL ,
    reason              VARCHAR2 (200) NOT NULL ,
    students_student_id NUMBER NOT NULL ,
    exams_exam_id       NUMBER NOT NULL
  ) ;
ALTER TABLE make_up_exams ADD CONSTRAINT make_up_exams_PK PRIMARY KEY ( make_up_id ) ;


CREATE TABLE registrations
  (
    registration_id     NUMBER NOT NULL ,
    student_id          NUMBER NOT NULL ,
    course_id           NUMBER NOT NULL ,
    registration_date   DATE NOT NULL ,
    courses_course_id   NUMBER NOT NULL ,
    students_student_id NUMBER NOT NULL
  ) ;
ALTER TABLE registrations ADD CONSTRAINT registrations_PK PRIMARY KEY ( registration_id ) ;


CREATE TABLE students
  (
    student_id        NUMBER NOT NULL ,
    first_name        VARCHAR2 (50) NOT NULL ,
    last_name         VARCHAR2 (50) NOT NULL ,
    email             VARCHAR2 (50) NOT NULL ,
    registration_date DATE NOT NULL
  ) ;
ALTER TABLE students ADD CONSTRAINT students_PK PRIMARY KEY ( student_id ) ;


ALTER TABLE courses ADD CONSTRAINT courses_instructors_FK FOREIGN KEY ( instructors_instructor_id ) REFERENCES instructors ( instructor_id ) ;

ALTER TABLE exam_enrollments ADD CONSTRAINT exam_enrollments_exams_FK FOREIGN KEY ( exams_exam_id ) REFERENCES exams ( exam_id ) ;

ALTER TABLE exam_enrollments ADD CONSTRAINT exam_enrollments_students_FK FOREIGN KEY ( students_student_id ) REFERENCES students ( student_id ) ;

ALTER TABLE exams ADD CONSTRAINT exams_courses_FK FOREIGN KEY ( courses_course_id ) REFERENCES courses ( course_id ) ;

ALTER TABLE make_up_exams ADD CONSTRAINT make_up_exams_exams_FK FOREIGN KEY ( exams_exam_id ) REFERENCES exams ( exam_id ) ;

ALTER TABLE make_up_exams ADD CONSTRAINT make_up_exams_students_FK FOREIGN KEY ( students_student_id ) REFERENCES students ( student_id ) ;

ALTER TABLE registrations ADD CONSTRAINT registrations_courses_FK FOREIGN KEY ( courses_course_id ) REFERENCES courses ( course_id ) ;

ALTER TABLE registrations ADD CONSTRAINT registrations_students_FK FOREIGN KEY ( students_student_id ) REFERENCES students ( student_id ) ;


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             0
-- ALTER TABLE                             15
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
