-- Generated by Oracle SQL Developer Data Modeler 4.1.1.888
--   at:        2024-10-06 17:06:04 PKT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g




CREATE TABLE billing
  (
    bill_id               NUMBER NOT NULL ,
    resident_id           NUMBER NOT NULL ,
    bill_date             DATE NOT NULL ,
    bill_due              NUMBER NOT NULL ,
    billing_cycle         NUMBER NOT NULL ,
    residents_resident_id NUMBER NOT NULL
  ) ;
ALTER TABLE billing ADD CONSTRAINT billing_PK PRIMARY KEY ( bill_id ) ;


CREATE TABLE feedbacks
  (
    feedback_id           NUMBER ,
    resident_id           NUMBER NOT NULL ,
    comments              VARCHAR2 (100) NOT NULL ,
    "date"                DATE NOT NULL ,
    residents_resident_id NUMBER NOT NULL
  ) ;


CREATE TABLE hostels
  (
    hostel_id NUMBER NOT NULL ,
    name      VARCHAR2 (50) NOT NULL
  ) ;
ALTER TABLE hostels ADD CONSTRAINT hostels_PK PRIMARY KEY ( hostel_id ) ;


CREATE TABLE inventory
  (
    inventory_id                 NUMBER NOT NULL ,
    name                         VARCHAR2 (50) NOT NULL ,
    quantity                     NUMBER NOT NULL ,
    reorder_level                NUMBER NOT NULL ,
    mess_operations_operation_id NUMBER NOT NULL
  ) ;
ALTER TABLE inventory ADD CONSTRAINT inventory_PK PRIMARY KEY ( inventory_id ) ;


CREATE TABLE meal_bookings
  (
    booking_id                   NUMBER NOT NULL ,
    resident_id                  NUMBER NOT NULL ,
    meal_plan_id                 NUMBER NOT NULL ,
    preference                   VARCHAR2 (100) NOT NULL ,
    restriction                  VARCHAR2 (100) NOT NULL ,
    allergy                      VARCHAR2 (100) NOT NULL ,
    meal_date                    DATE NOT NULL ,
    guest_meals                  VARCHAR2 (50) NOT NULL ,
    booking_status               VARCHAR2 (50) NOT NULL ,
    meal_plans_meal_plan_id      NUMBER NOT NULL ,
    residents_resident_id        NUMBER NOT NULL ,
    mess_operations_operation_id NUMBER NOT NULL
  ) ;
ALTER TABLE meal_bookings ADD CONSTRAINT meal_bookings_PK PRIMARY KEY ( booking_id ) ;


CREATE TABLE meal_plans
  (
    meal_plan_id          NUMBER NOT NULL ,
    OPTIONS               VARCHAR2 (50) NOT NULL ,
    preferences           VARCHAR2 (50) NOT NULL ,
    residents_resident_id NUMBER NOT NULL
  ) ;
ALTER TABLE meal_plans ADD CONSTRAINT meal_plans_PK PRIMARY KEY ( meal_plan_id ) ;


CREATE TABLE mess_operations
  (
    operation_id NUMBER NOT NULL ,
    timing       DATE NOT NULL ,
    dining_area  VARCHAR2 (50) NOT NULL ,
    inventory_id NUMBER NOT NULL
  ) ;
ALTER TABLE mess_operations ADD CONSTRAINT mess_operations_PK PRIMARY KEY ( operation_id ) ;


CREATE TABLE residents
  (
    resident_id       NUMBER NOT NULL ,
    meal_plan_id      NUMBER NOT NULL ,
    name              VARCHAR2 (50) NOT NULL ,
    hostel_id         NUMBER NOT NULL ,
    room_number       NUMBER NOT NULL ,
    phone_number      NUMBER NOT NULL ,
    hostels_hostel_id NUMBER NOT NULL
  ) ;
ALTER TABLE residents ADD CONSTRAINT residents_PK PRIMARY KEY ( resident_id ) ;


ALTER TABLE billing ADD CONSTRAINT billing_residents_FK FOREIGN KEY ( residents_resident_id ) REFERENCES residents ( resident_id ) ;

ALTER TABLE feedbacks ADD CONSTRAINT feedbacks_residents_FK FOREIGN KEY ( residents_resident_id ) REFERENCES residents ( resident_id ) ;

ALTER TABLE inventory ADD CONSTRAINT inventory_mess_operations_FK FOREIGN KEY ( mess_operations_operation_id ) REFERENCES mess_operations ( operation_id ) ;

ALTER TABLE meal_bookings ADD CONSTRAINT meal_bookings_meal_plans_FK FOREIGN KEY ( meal_plans_meal_plan_id ) REFERENCES meal_plans ( meal_plan_id ) ;

ALTER TABLE meal_bookings ADD CONSTRAINT meal_bookings_mess_operations_FK FOREIGN KEY ( mess_operations_operation_id ) REFERENCES mess_operations ( operation_id ) ;

ALTER TABLE meal_bookings ADD CONSTRAINT meal_bookings_residents_FK FOREIGN KEY ( residents_resident_id ) REFERENCES residents ( resident_id ) ;

ALTER TABLE meal_plans ADD CONSTRAINT meal_plans_residents_FK FOREIGN KEY ( residents_resident_id ) REFERENCES residents ( resident_id ) ;

ALTER TABLE residents ADD CONSTRAINT residents_hostels_FK FOREIGN KEY ( hostels_hostel_id ) REFERENCES hostels ( hostel_id ) ;


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             8
-- CREATE INDEX                             0
-- ALTER TABLE                             15
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
