//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication11.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int AttendanceID { get; set; }
        public Nullable<int> EnrollmentID { get; set; }
        public Nullable<System.DateTime> AttendanceDate { get; set; }
        public string Status { get; set; }
    
        public virtual Enrollment Enrollment { get; set; }
    }
}
