//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication11.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseOffering
    {
        public CourseOffering()
        {
            this.Enrollments = new HashSet<Enrollment>();
            this.Timetables = new HashSet<Timetable>();
        }
    
        public int OfferingID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> FacultyID { get; set; }
        public string Semester { get; set; }
        public Nullable<int> Year { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Faculty Faculty { get; set; }
        public virtual ICollection<Enrollment> Enrollments { get; set; }
        public virtual ICollection<Timetable> Timetables { get; set; }
    }
}
