//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication11.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faculty
    {
        public Faculty()
        {
            this.CourseOfferings = new HashSet<CourseOffering>();
        }
    
        public int FacultyID { get; set; }
        public string FacultyName { get; set; }
        public Nullable<int> DeptID { get; set; }
    
        public virtual ICollection<CourseOffering> CourseOfferings { get; set; }
        public virtual Department Department { get; set; }
    }
}
