//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication11.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classroom
    {
        public Classroom()
        {
            this.Timetables = new HashSet<Timetable>();
        }
    
        public int RoomID { get; set; }
        public string Building { get; set; }
        public Nullable<int> Capacity { get; set; }
    
        public virtual ICollection<Timetable> Timetables { get; set; }
    }
}
