//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication11.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Admins = new HashSet<Admin>();
            this.Courses = new HashSet<Course>();
            this.Faculties = new HashSet<Faculty>();
            this.Students = new HashSet<Student>();
        }
    
        public int DeptID { get; set; }
        public string DeptName { get; set; }
    
        public virtual ICollection<Admin> Admins { get; set; }
        public virtual ICollection<Course> Courses { get; set; }
        public virtual ICollection<Faculty> Faculties { get; set; }
        public virtual ICollection<Student> Students { get; set; }
    }
}
